Revert "Unit test expansion (#75)"
This isn't a backwards compatable change as it break our cisco.asa
collection. As it is using

  File "/home/zuul/.ansible/collections/ansible_collections/cisco/asa/plugins/module_utils/network/asa/asa.py", line 35, in <module>
    from ansible_collections.ansible.netcommon.plugins.module_utils.network.common.utils import (
ImportError: cannot import name EntityCollection

This reverts commit eeb6b5bafa2b30d2b806f45f38e4be96b8bba35e.

Signed-off-by: Paul Belanger <pabelanger@redhat.com>